using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Demos.HackerU.HomeWork.Store
{
    public class StoreProduct
    {
        private static int idCounter = 0;
        private readonly string PrefixId;
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public bool Isinstock { get; set; }
        public int CategoryId { get; set; }


        public StoreProduct(string prefixId, int categoryId, string name, decimal price, bool isInStock)
        {
            idCounter++;
            Id = idCounter;
            PrefixId = $"{prefixId}#{Id}";
            Name = name;
            Price = price;
            Isinstock = isInStock;
            CategoryId = categoryId;
        }

        public StoreProduct(int categoryId, string name, decimal price, bool isInStock)
        {
            idCounter++;
            Id = idCounter;
            PrefixId = $"{categoryId}#{Id}";
            Name = name;
            Price = price;
            Isinstock = isInStock;
            CategoryId = categoryId;
        }

        public StoreProduct()

        {
            idCounter++;
            Id = idCounter;
            PrefixId = $"{CategoryId}#{Id}";
            Name = "No Name";
            Price = 0;
            Isinstock = false;
            CategoryId = 0;
        }

        public static StoreProduct CopyProductWithNewId(StoreProduct exsistingProduct)
        {

            idCounter++;
            StoreProduct newProduct = exsistingProduct;
            newProduct.Id = idCounter;

            return newProduct;
        }
        //Id Generated by the same as in constractor

        public override string ToString()
        {
            return $"Id :{Id}, Name :{Name}, Price :{Price} ,Isinstock :{Isinstock} ,CategoryId :{CategoryId}, PrefixId :{PrefixId}";
        }

    }
}
