// <auto-generated />
using Demos.HackerU.HomeWork.HW_20;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demos.HackerU.HomeWork.Migrations
{
    [DbContext(typeof(UsersDbContext))]
    [Migration("20230602135429_Hw20v1")]
    partial class Hw20v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demos.HackerU.HomeWork.HW_20.Roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("Demos.HackerU.HomeWork.HW_20.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("RolesUsers", b =>
                {
                    b.Property<int>("_rolesid")
                        .HasColumnType("int");

                    b.Property<int>("_usersid")
                        .HasColumnType("int");

                    b.HasKey("_rolesid", "_usersid");

                    b.HasIndex("_usersid");

                    b.ToTable("RolesUsers");
                });

            modelBuilder.Entity("RolesUsers", b =>
                {
                    b.HasOne("Demos.HackerU.HomeWork.HW_20.Roles", null)
                        .WithMany()
                        .HasForeignKey("_rolesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Demos.HackerU.HomeWork.HW_20.Users", null)
                        .WithMany()
                        .HasForeignKey("_usersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
